import type { Metadata } from "next";
import { Nosifer, Alegreya,} from "next/font/google";
import "./globals.css";

const nosifer = Nosifer({
  variable: "--font-nosifer",
    weight: "400",
    subsets: ["latin"],
    preload: false,
  });

const alegreya = Alegreya({
  variable: "--font-alegreya",
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Bloody Espresso",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nosifer.variable} ${alegreya.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
